sudo: required
language: sh

os:
- osx
- linux
- windows

script:
- sh install-stack.sh
- stack --version
- echo $PATH
- curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -s -- --version
- curl -sSL https://raw.github.com/ndmitchell/weeder/master/misc/travis.sh | sh -s -- --version
