sudo: required
language: sh

os:
- osx
- linux
- windows

script:
- curl -sSL https://get.haskellstack.org/ | sh
- stack --version
- curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s -- --version
- curl -sSL https://raw.github.com/ndmitchell/weeder/master/misc/run.sh | sh -s -- --version
