build: off
image:
- Visual Studio 2017
- Ubuntu

environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true

test_script:
- sh install-stack.sh
- stack --version
- curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -s -- --version
- curl -sSL https://raw.github.com/ndmitchell/weeder/master/misc/travis.sh | sh -s -- --version
- ps: Invoke-Command ([Scriptblock]::Create((Invoke-WebRequest 'https://raw.githubusercontent.com/ndmitchell/hlint/master/misc/appveyor.ps1').Content)) -ArgumentList @('--version')
- ps: Invoke-Command ([Scriptblock]::Create((Invoke-WebRequest 'https://raw.githubusercontent.com/ndmitchell/weeder/master/misc/appveyor.ps1').Content)) -ArgumentList @('--version')
