# Azure Pipelines file, see https://aka.ms/yaml

trigger:
- master

strategy:
  matrix:
    linux:   {image: "Ubuntu 16.04"}
    windows: {image: "vs2017-win2016"}
    mac:     {image: "macOS-10.13"}

pool: {vmImage: '$(image)'}
steps:
- script: |
    which 7z
    set -e
    sh install-stack.sh
    stack --version
    curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -x -s -- --version
    curl -sSL https://raw.github.com/ndmitchell/weeder/master/misc/travis.sh | sh -x -s -- --version
    stackk --version
    stack --version
