# Azure Pipelines file, see https://aka.ms/yaml

trigger:
- master

jobs:
- job: Windows
  pool: {vmImage: 'vs2017-win2016'}
  steps:
  - script: |
      set -e
      sh install-stack.sh
      stack --version
      curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -x -s -- --version
      curl -sSL https://raw.github.com/ndmitchell/weeder/master/misc/travis.sh | sh -x -s -- --version
- job: Linux
  pool: {vmImage: "Ubuntu 16.04"}
  steps:
  - script: |
      set -e
      sh install-stack.sh
      stack --version
      curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -x -s -- --version
      curl -sSL https://raw.github.com/ndmitchell/weeder/master/misc/travis.sh | sh -x -s -- --version
- job: Mac
  pool: {vmImage: "macOS-10.13"}
  steps:
  - script: |
      set -e
      sh install-stack.sh
      stack --version
      curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -x -s -- --version
      curl -sSL https://raw.github.com/ndmitchell/weeder/master/misc/travis.sh | sh -x -s -- --version
