version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout
      - run: sh install-stack.sh
      - run: stack --version
      - run: curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s -- --version
      - run: curl -sSL https://raw.github.com/ndmitchell/weeder/master/misc/run.sh | sh -s -- --version
